# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('url', models.URLField(verbose_name='链接')),
                ('mime_type', models.CharField(max_length=32)),
                ('hash', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
