# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:41
from __future__ import unicode_literals

import discuss.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True)),
                ('id', models.CharField(default=discuss.models.discuss_unique_uuid, editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='uuid')),
                ('content', models.TextField(blank=True, max_length=1024)),
                ('status', models.IntegerField(choices=[(0, '验证用户评论'), (1, '待批准'), (2, '已批准'), (-1, '被拒绝'), (-2, '被删除')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
