# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_auto_20160530_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
