# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0005_discuss_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
